# Generated by Django 3.2.5 on 2021-07-08 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210708_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Tag',
        ),
        migrations.AddField(
            model_name='product',
            name='Tag',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
